name: Validate Renovate Configs
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/renovate.yml' # this file
      - 'renovate/default.json'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/renovate.yml' # this file
      - 'renovate/default.json'

permissions:
  contents: read

jobs:
  renovate:
    name: Check Renovate Configs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Validate Renovate Config
        uses: rinchsan/renovate-config-validator@v0.2.1
        with:
          pattern: 'renovate/default.json'
